project_id = "pssoincihmbspzkqcynu"

[functions.create-organization-with-admin]
verify_jwt = true

[functions.dashboard-stats]
verify_jwt = false

[functions.recent-activity]
verify_jwt = true

[functions.generate-billing-excel]
verify_jwt = false